"""create alert_registrations table

Revision ID: 4ee79f900dc6
Revises: 
Create Date: 2026-02-27 15:58:12.206330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee79f900dc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('bus_line', sa.String(), nullable=False),
    sa.Column('stop_lat', sa.Float(), nullable=False),
    sa.Column('stop_lon', sa.Float(), nullable=False),
    sa.Column('window_start', sa.String(), nullable=False),
    sa.Column('window_end', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_registrations_bus_line'), 'alert_registrations', ['bus_line'], unique=False)
    op.create_index(op.f('ix_alert_registrations_id'), 'alert_registrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_registrations_id'), table_name='alert_registrations')
    op.drop_index(op.f('ix_alert_registrations_bus_line'), table_name='alert_registrations')
    op.drop_table('alert_registrations')
    # ### end Alembic commands ###
