"""add stop_name to alert_registrations

Revision ID: 5f62c01635fa
Revises: aed9af601d77
Create Date: 2026-03-04 13:40:56.664182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f62c01635fa'
down_revision: Union[str, Sequence[str], None] = 'aed9af601d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_registrations', sa.Column('stop_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_registrations', 'stop_name')
    # ### end Alembic commands ###
