"""add last_alerted_date to alert_registrations

Revision ID: aed9af601d77
Revises: 4ee79f900dc6
Create Date: 2026-02-28 11:15:56.164614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed9af601d77'
down_revision: Union[str, Sequence[str], None] = '4ee79f900dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_registrations', sa.Column('last_alerted_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_registrations', 'last_alerted_date')
    # ### end Alembic commands ###
